### ISSUE TITLE
Bump required Go version to at least 1.8

### ISSUE THREAD

**Issue by danmx** [beego/bee#619]
I can't `go get` when using `go` version `1.7`.

```console
$ go get -u github.com/beego/bee
# github.com/beego/bee/cmd/commands/run
../../../github.com/beego/bee/cmd/commands/run/watch.go:88: undefined: time.Until
# github.com/beego/bee/cmd/commands/dlv
../../../github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:230: undefined: time.Until
``` 

It seems to work with `1.8`.

I'd suggest testing it with older versions too or recommend the one that you're using:
https://github.com/beego/bee/blob/815bdd7/.travis.yml#L3

**Comment by askuy** [comment]
use go > 1.12
go get github.com/beego/bee
